config/routes.rb
Homepage::Application.routes.draw do
  resources :pages
  get '(errors)/:status' => 'errors#show', constraints: {status: /\d{3}/}
  get 'schedules' => 'schedules#index', as: :index_schedules
  get 'robots.txt' => 'robots#index'
  get 'sitemap.xml' => 'robots#sitemap'
  root "pages#index"
  get ':id' => 'pages#show', as: :pg, constraints: { id: /.*/ }

end

app/models/page.rb
# Gollum file
class Page < GollumRails::Page
  alias_method :title, :meta_title

  def date
    meta["date"] || Time.at(0)
  end
  def start
    DateTime.parse(meta["start"].to_s) || DateTime.new(1970)
  end

  def end
    DateTime.parse(meta["end"].to_s) || DateTime.new(1970)
  end


  def keywords
    meta["keywords"] || nil
  end

  def description
    meta["description"] || nil
  end
  alias_method :html_data, :html_without_yaml 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
  session :off 
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #
  before_filter :initialize_empty_meta

  rescue_from  ActionController::RoutingError,with: :handle_404

  def handle_404(exception)
    render 'errors/404'
  end

  private

  def initialize_empty_meta
    @meta ||= {}
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def show
    @exception = env["action_dispatch.exception"]
    respond_to do |format|
      format.html{ render '404'}
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all(folder: 'articles')
    @pages.sort!{ |b,a| a.date <=> b.date}
    respond_to do |format|
      format.html{}
      format.json do
        render json: @pages.map{ |p| {title: p.title,date: p.date.to_i * 1000, text: p.html_data}}
      end
    end
  end

  def show
    @page = Page.find(params[:id], Page.wiki.ref, true, false)
    if @page
      @meta[:description] = @page.description if @page.description
      @meta[:keywords] = @page.keywords if @page.keywords
    else
      render_404
    end
  end

  private
  def render_404
    raise ActionController::RoutingError.new('No such Article found')
  end
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  def index
    render 'index.text.erb',layout: false
  end
  def sitemap
    @pages = Page.all(folder: 'articles')
    render 'sitemap.xml.erb', layout: false
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index

    date = DateTime.current
    @cur_month = Date::MONTHNAMES[date.month]
    @cur_year = date.year

    @pages = Page.tree(folder: "schedule/#{date.year}/#{@cur_month}")

    @pages.map!{|p| Page.find(File.join(File.dirname(p.path),File.basename(p.path,File.extname(p.path))))}
    @pages.sort!{ |a,b| a.start <=> b.start}
    @pages.reject!{ |p| p.end < Time.zone.now }

    respond_to do |format|
      format.json do
        render json: @pages.map{ |p| {title: p.title,start: p.start.to_i * 1000, text: p.html_data}}
       end
      format.html { render :index}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def dart_include_tag
    content_tag(:script, nil, :src => "/assets/main.dart", :type => 'application/dart') +
    content_tag(:script, nil, src: asset_path("dart.js"), type: 'text/javascript')
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="utf-8">
  <title>FlorianKasper.org</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <meta name="author" content="Florian Kasper">
  <meta name="description" content="<%= @meta[:description] || 'my blog about all interesting things in technology.' %>">
  <meta name="keywords" content="<%= @meta[:keywords] ? @meta[:keywords].join(',') : 'ruby,html,dart,scala,javascript,coffeescript,redmine,gollum' %>">
  <meta name="robots" content="index, follow">
  <meta name="google-site-verification" content="gMnbWeEF0gJFe3XMioTGY75yGX2ypxKLfQckVsox6cM" />
  <link rel="apple-touch-icon" href="<%= asset_path('apple-touch-icon-iphone.png') %>" />
  <link rel="apple-touch-icon" sizes="72x72" href="<%= asset_path('apple-touch-icon-ipad.png') %>"  />
  <link rel="apple-touch-icon" sizes="114x114" href="<%= asset_path('apple-touch-icon-iphone4.png') %>" />
  <link rel='icon' type='image/png' href="<%= asset_path('favicon.png') %>">

  <%= stylesheet_link_tag    "application" %>

</head>
<body>
  <nav class="top-nav __heading--main">
    <div class="upper-nav __heading--sub-main">
      <h1 class="__heading--title typography--PRIMARY-HEADING magic--hideif--IPHONE"><%=link_to "Florian Kasper", root_path %></h1>
      <h1 class="__heading--title typography--PRIMARY-HEADING magic--displayif--IPHONE"><%=link_to "Florian", root_path %></h1>
    </div>
    <div class="lower-nav __heading--sub-secondary">
      <ul class="nav-bar __heading--icons">
        <li><%= link_to index_schedules_path do%><i class="fa fa-calendar"></i><% end%></li>
        <li><a href="https://github.com/nirnanaaa"><i class="fa fa-github"></i></a></li>
        <li><a href="https://twitter.com/officiallyzyg"><i class="fa fa-twitter"></i></a></li>
      </ul>
    </div>
  </nav>
  
  <div class="body">
    <div class="inner">
      <%= yield %>
    </div>
  </div>
  
  <%= stylesheet_link_tag    "fonts" %>
 </body>
</html>

app/views/pages/index.html.erb
<% @pages.each do |page| %>
  <section class="pages">
    <div class="schedule-top">
      <h2 class="__article--title"><%= link_to page.title, pg_path(Gollum::Page.cname(page.name)) %></h2>
      <div class="__article--date"><%= Time.parse(page.date.to_s).strftime("%d-%m-%Y") %></div>
    </div>
    <div class="clearfix"></div>
    <div class="description typography--AREA"> <%= page.html_data.html_safe%></div>
  </section>
<% end%>

app/views/pages/show.html.erb
<article class="__article--main">
  <h2 class="__article--title typography--SECONDARY-HEADING"><%= @page.title %></h2>
  <div class="__article--date typography--DATE"><%= Time.parse(@page.date.to_s).strftime("%d-%m-%Y") %></div>
  <div class="__article--description typography--AREA"><%= @page.html_data.html_safe %></div>
</article> 
<script type="text/javascript">
    var disqus_shortname = 'nirnanaaa'; // Required - Replace example with your forum shortname
    var disqus_identifier = '<%= @page.url%>';

    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>

<aside class="__comments--main">
  <div id="disqus_thread"></div>
</aside>

app/views/robots/index.text.erb
User-agent: *
Disallow: 
Disallow: /cgi

app/views/robots/sitemap.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <% @pages.each do |page| %>
    <sitemap>
      <loc>https://floriankasper.org<%= url_for pg_path(Gollum::Page.cname(page.name)) %></loc>
      <lastmod><%= Time.parse(page.date).strftime( "%Y-%m-%dT%H:%M:%SZ" ) %></lastmod>
      <changefreq>monthly</changefreq>
   </sitemap>
 <% end %>
</sitemapindex>

app/views/schedules/index.html.erb
<section class="pages">
  <div class="schedule-top">
    <h2 class="__article--title">Schedule for <%=@cur_month%> <%=@cur_year%></h2>
  </div>
  <div class="clearfix"></div>
  <% @pages.each do |page| %>
    <div class="description typography--AREA"> 
      <div class="__schedule--title">
        <%= link_to page.title, pg_path(Gollum::Page.cname(page.name)) %>
      </div>
      <div class="__schedule--date">
        <%if page.end.nil? || page.start == page.end %>
          <%= page.start.strftime("%e %B %k:%M")%>
        <%else%>
          <%= page.start.strftime("%e %B %k:%M")%> - <%=page.end.strftime("%e %B %k:%M")%>
        <%end%>
      </div>
    </div>
  <% end%>
</section>